#!/usr/bin/python
import web
urls = ('/','index')

class index:
  def __init__(self):
      self.render = web.template.render('webpy/')
  
  def GET(self):
    return self.render.index()
    
if __name__ == "__main__":
  app = web.application(urls,globals())
